name: ClashOneBlockRace
version: '1.0-SNAPSHOT'

main: dev.limanoel.clashOneBlockRace.ClashOneBlockRace
api-version: '1.21.11'
load: POSTWORLD

authors: [ Limanoel for ClashCube ]

commands:
  oneblockrace:
    description: Join the one block race
    usage: /<command> [singleplayer|multiplayer]
    aliases: [oneblock, oneblockrace, obr]
  leave:
    description: Leave the current OneBlock match
    usage: /leave
    aliases: [l, obleave, oneblockleave]
